name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@dev.srv.zoworld.io "echo 'SSH connection successful!'"
        shell: bash

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@dev.srv.zoworld.io << 'ENDSSH'
            cd /var/www/zostel-whatsapp
            git pull origin master
            npm install
            sudo systemctl reload nginx
          ENDSSH
        shell: bash
